### ISSUE TITLE
Gifs have static

### ISSUE THREAD

**Issue by Paladinknightprime** [110Percent/beheeyem#2]
Some of the gifs for pokemon look like they have static and just look blurry

**Comment by shirt-dev** [comment]
I believe this is because they are resized.

**Comment by 110Percent** [comment]
This is an issue with the way images are handled by your device. Certain images appear normally on some devices, whereas they appear staticy on others. I'm looking into fixing this, but I don't have a definite solution as of now.

**Comment by 110Percent** [comment]
Sorry for the late reply. The issue has been fixed in a recent commit.

**Comment by phi-line** [comment]
I'm curious how you managed to have the embedded gif autoplay.
